# Generated by Django 4.0 on 2022-01-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.authenticationkeys')),
            ],
            options={
                'db_table': 'auth_platform_permissions',
            },
        ),
    ]
