# Generated by Django 4.0 on 2022-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='authpermissions',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
