# Generated by Django 4.0 on 2022-01-05 10:05

from django.db import migrations, models
import django.db.models.deletion
import queries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technology', '0001_initial'),
        ('myUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('file_path', models.FileField(blank=True, upload_to=queries.models.nameFile)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technology.technology')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myUsers.customuser')),
            ],
        ),
    ]
