# Generated by Django 4.0 on 2022-01-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='queries',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
