# Generated by Django 4.0 on 2022-01-06 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='queries.queries'),
        ),
    ]
