# Generated by Django 4.0 on 2022-01-19 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_alter_queries_description_alter_queries_title'),
        ('responses', '0002_alter_responses_q_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='q_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='queries.queries'),
        ),
    ]
