# Generated by Django 4.0 on 2022-01-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUsers', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
